name: Appium Java Android Test Automation CI

on:
  push:
    branches:
      - main
      - feat/*
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Install Android SDK Components
        run: |
          sdkmanager "system-images;android-30;google_apis;x86"  # Install required system images for emulator

      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Install Appium server and Appium android driver
        run: |
          npm install -g appium
          appium -v
          appium driver install uiautomator2

      - name: Execute Android all test suites
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          profile: Nexus_5X
          arch: x86
          emulator-options: '-no-window -no-audio'
          script: |
            adb wait-for-device
            sleep 60  # Wait for extra time to ensure the emulator has fully booted
            adb shell getprop sys.boot_completed | grep -m 1 '1'
            mvn clean install -DskipTests
            mvn test || true

      - name: Generate Allure Report
        run: mvn allure:report || true

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: target/allure-report
