name: Appium Java Android Test Automation CI

on:
  push:
    branches:
      - main
      - feat/*
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests (test, staging, production)'
        required: true
        default: 'test'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [test, staging, production]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '14'
          distribution: 'temurin'

      - name: Cache Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Build with Maven
        run: mvn -B clean compile

      - name: Run Tests with Maven Profile ${{ matrix.environment }}
        run: mvn -B test -P${{ matrix.environment }}

      - name: Generate Allure Report
        run: mvn allure:report || true

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: target/allure-report

